/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateUserDetailArgs } from "./CreateUserDetailArgs";
import { UpdateUserDetailArgs } from "./UpdateUserDetailArgs";
import { DeleteUserDetailArgs } from "./DeleteUserDetailArgs";
import { UserDetailFindManyArgs } from "./UserDetailFindManyArgs";
import { UserDetailFindUniqueArgs } from "./UserDetailFindUniqueArgs";
import { UserDetail } from "./UserDetail";
import { User } from "../../user/base/User";
import { UserDetailService } from "../userDetail.service";

@graphql.Resolver(() => UserDetail)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class UserDetailResolverBase {
  constructor(
    protected readonly service: UserDetailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserDetail",
    action: "read",
    possession: "any",
  })
  async _userDetailsMeta(
    @graphql.Args() args: UserDetailFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [UserDetail])
  @nestAccessControl.UseRoles({
    resource: "UserDetail",
    action: "read",
    possession: "any",
  })
  async userDetails(
    @graphql.Args() args: UserDetailFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<UserDetail[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "UserDetail",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => UserDetail, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserDetail",
    action: "read",
    possession: "own",
  })
  async userDetail(
    @graphql.Args() args: UserDetailFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<UserDetail | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "UserDetail",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => UserDetail)
  @nestAccessControl.UseRoles({
    resource: "UserDetail",
    action: "create",
    possession: "any",
  })
  async createUserDetail(
    @graphql.Args() args: CreateUserDetailArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<UserDetail> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "UserDetail",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"UserDetail"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        userId: args.data.userId
          ? {
              connect: args.data.userId,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => UserDetail)
  @nestAccessControl.UseRoles({
    resource: "UserDetail",
    action: "update",
    possession: "any",
  })
  async updateUserDetail(
    @graphql.Args() args: UpdateUserDetailArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<UserDetail | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "UserDetail",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"UserDetail"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          userId: args.data.userId
            ? {
                connect: args.data.userId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserDetail)
  @nestAccessControl.UseRoles({
    resource: "UserDetail",
    action: "delete",
    possession: "any",
  })
  async deleteUserDetail(
    @graphql.Args() args: DeleteUserDetailArgs
  ): Promise<UserDetail | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserDetail",
    action: "read",
    possession: "any",
  })
  async userId(
    @graphql.Parent() parent: UserDetail,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUserId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
