/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssetUpdateManyWithoutUsersInput } from "./AssetUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { TaskUpdateManyWithoutUsersInput } from "./TaskUpdateManyWithoutUsersInput";
import { UserDetailUpdateManyWithoutUsersInput } from "./UserDetailUpdateManyWithoutUsersInput";
@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AssetUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AssetUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AssetUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  assets?: AssetUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @IsOptional()
  @Field(() => [String], {
    nullable: true,
  })
  roles?: Array<string>;

  @ApiProperty({
    required: false,
    type: () => TaskUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TaskUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TaskUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  tasks?: TaskUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserDetailUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserDetailUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserDetailUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  userDetails?: UserDetailUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}
export { UserUpdateInput };
